source "https://rubygems.org"

gem "puma", "~> 6.0"
gem "sinatra", "~> 3.1", require: 'sinatra/base'
gem "sinatra-contrib", "~> 3.1"
gem "omniauth", "~> 1.9"
gem "omniauth-salesloft"
gem "securerandom"
gem "httparty"
gem "rspec"
gem "dotenv"
gem "byebug"
gem "activesupport"
gem "jose"
gem "redis"
